baseurl = "/"
title = "Reberti Carvalho Soares"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"
relativeURLs = false
uglyURLs = false

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disable_comments = false

[params]
    author = "Reberti"
    info = "Programmer and Linux SysAdm"
    description = "Reberti's personal website"
    keywords = "blog,developer,personal,linux"
    avatarurl = "/img/avatar.png"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    footercontent = "FOSS developer and activist. UNIX enthusiast. KISS preacher."
    commit = "https://gitlab.com/KisuYami/kblog/-/commits/master"

    hidecredits = false
    hidecopyright = false

    rtl = false

    math = true

    colorscheme = "auto"

    enableTwemoji = true

# Social links
[[params.social]]
    name = "Gitlab"
    #icon = "fab fa-gitlab"
    weight = 1
    url = "https://gitlab.com/kisuyami/"
[[params.social]]
    name = "Reddit"
    #icon = "fab fa-github"
    weight = 2
    url = "https://www.reddit.com/user/reberti666/"
[[params.social]]
    name = "Twitter"
    #icon = "fab fa-twitter"
    weight = 3
    url = "https://twitter.com/kisoyami/"
[[params.social]]
    name = "Mastodon"
    #icon = "fab fa-mastodon"
    weight = 3
    url = "https://fosstodon.org/@kisuyami"

[[menu.main]]
    name = "Projects"
    weight = 1
    url = "/projects/"
[[menu.main]]
    name = "About"
    weight = 3
    url = "/about/"

[languages]
    [languages.en]
        languagename = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "Projects"
            weight = 1
            url = "projects/"

            [[languages.en.menu.main]]
            name = "About"
            weight = 3
            url = "about/"

    [languages.pt-br]
        languagename = "Português"
        title = "Reberti Carvalho Soares"

        [languages.pt-br.params]
            author = "KisuYami"
            info = "Desenvolvedor FOSS e Linux SysAdm"
    	    description = "A pagina pessoal do KisuYami"
    	    keywords = "blog,desenvolvedor,pessoal,linux"
    	    footercontent = "Desenvolvedor e activista FOSS . Entusiasta de UNIX."

        [languages.pt-br.menu]

            [[languages.pt-br.menu.main]]
            name = "Projetos"
            weight = 1
            url = "projects/"

            [[languages.pt-br.menu.main]]
            name = "Sobre"
            weight = 3
            url = "about/"
