baseurl = "/"
title = "Reberti Carvalho Soares"
theme = "hugo-coder"
languagecode = "pt-br"
defaultcontentlanguage = "pt-br"
relativeURLs = false
uglyURLs = false

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disable_comments = true

[params]
    author = "RebertiCS"
    info = "Programador Full-Stack e Administrador DevOps"
    description = "A pagina pessoal do RebertiCS"
    keywords = "Densenvolvedor, Full Stack, Linux, Django, Python, DevOps"
    avatarurl = "/img/avatar.png"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    footercontent = "Contato pelo LinkedIn: RebertiCS"
    commit = "https://github.com/RebertiCS/github.rebertics.io.git/commits/master"

    hidecredits = true
    hidecopyright = true

    rtl = false

    math = true

    colorscheme = "auto"

    enableTwemoji = true

[markup.highlight]
    style = "github-dark"

# Social links
[[params.social]]
    name = "Github"
    icon = "fa fa-2x fa-github"
    weight = 1
    url = "https://github.com/RebertiCS"
[[params.social]]
    name = "LinkedIn"
    icon = "fa fa-2x fa-linkedin"
    weight = 1
    url = "https://www.linkedin.com/in/rebertics/"
[[params.social]]
    name = "XDA"
    #icon = "fa fa-2x fa-xda"
    weight = 3
    url = "https://xdaforums.com/m/rebertics.12774596/"

[[menu.main]]
    name = "Projetos"
    weight = 1
    url = "/projects/"
[[menu.main]]
  name = "Blog"
  weight = 2
  url  = "posts/"
[[menu.main]]
    name = "Sobre o Author"
    weight = 3
    url = "/about/"
